name: Remote SSH Command
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          password: ${{ secrets.PASSWORD }}
          script: whoami
